[tool.poetry]
name = "hh-dolg"
version = "0.1.0"
description = ""
authors = ["Pavel Artiev <pavelshapovalov.00@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
requests = "^2.32.3"
black = "^25.1.0"
isort = "^6.0.1"
mypy = "^1.15.0"
pytest = "^8.3.5"
psycopg2 = "^2.9.10"
python-dotenv = "^1.1.0"
binary = "^1.0.1"
flake8 = "^7.2.0"
pathlib = "^1.0.1"
certifi = "^2025.1.31"
charset-normalizer = "^3.4.1"
click = "^8.1.8"
colorama = "^0.4.6"
configparser = "^7.2.0"
idna = "^3.10"
mccabe = "^0.7.0"
mypy-extensions = "^1.1.0"
packaging = "^25.0"
pathspec = "^0.12.1"
platformdirs = "^4.3.7"
pycodestyle = "^2.13.0"
pyflakes = "^3.3.2"
sql = "^2022.4.0"
typing-extensions = "^4.13.2"
urllib3 = "^2.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
